# Generated by Django 4.0.2 on 2022-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('num_reg', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='N° de Registro')),
            ],
            options={
                'ordering': ['num_reg'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('año', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto')], verbose_name='Año')),
                ('division', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera'), (4, 'Cuarta'), (5, 'Quinta'), (6, 'Sexta')], verbose_name='División')),
                ('cant_alumnos', models.IntegerField(verbose_name='Cantidad de Alumnos')),
            ],
            options={
                'ordering': ['año', 'division'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_cuit', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='N° de CUIT/CUIL')),
                ('num_doc', models.CharField(max_length=10, verbose_name='N° de documento')),
                ('apellido', models.CharField(max_length=90, verbose_name='Apellido/s')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre/s')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=120, verbose_name='Calle y número')),
                ('telefono', models.CharField(max_length=14, verbose_name='N° de teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_genero', to='escuela.genero')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
