# Generated by Django 4.0.2 on 2022-06-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_alter_aula_idaula_alter_preceptor_idpreceptor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicta',
            options={'ordering': ['profesor_id_profesor', 'materia_codigo', 'cargo'], 'verbose_name_plural': 'Dictan'},
        ),
        migrations.AlterModelOptions(
            name='preceptor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Preceptores'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='rinde',
            options={'ordering': ['materia_codigo', 'alumno_nro_registro'], 'verbose_name_plural': 'Rinden'},
        ),
        migrations.AlterModelOptions(
            name='tiene',
            options={'ordering': ['aula_idAula', 'hora_ingreso', 'hora_egreso'], 'verbose_name_plural': 'Tienen'},
        ),
    ]
